name: ExoCTK

channels:
    - astropy
    - http://ssb.stsci.edu/astroconda

dependencies:
    - astropy
    - Cython
    - matplotlib
    - numpy
    - scipy
    - numba
    - h5py

   - pip:
       - batman-package
