name: exoctk-3.7
channels:
  - defaults
dependencies:
  - alabaster=0.7.12
  - asn1crypto=0.24.0
  - astropy=3.0.5
  - atomicwrites=1.2.1
  - attrs=18.2.0
  - babel=2.6.0
  - blas=1.0
  - bokeh=1.0.2
  - ca-certificates=2018.03.07
  - certifi=2018.10.15
  - cffi=1.11.5
  - chardet=3.0.4
  - click=7.0
  - cryptography
  - cycler=0.10.0
  - cython=0.29
  - docutils=0.14
  - flask=1.0.2
  - freetype=2.9.1
  - h5py=2.8.0
  - hdf5=1.10.2
  - idna=2.7
  - imagesize=1.1.0
  - intel-openmp=2019.1
  - itsdangerous=1.1.0
  - jinja2=2.10
  - jpeg=9b
  - kiwisolver=1.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libpng=1.6.35
  - libtiff=4.0.9
  - llvmlite=0.26.0
  - markupsafe=1.1.0
  - matplotlib
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - mock=2.0.0
  - more-itertools=4.3.0
  - ncurses=6.1
  - numba=0.41.0
  - numpy=1.15.4
  - numpy-base=1.15.4
  - olefile=0.46
  - openssl=1.1.1a
  - packaging=18.0
  - pandas=0.23.4
  - pbr=5.1.1
  - pillow=5.3.0
  - pip=18.1
  - pluggy=0.8.0
  - psutil=5.4.8
  - py=1.7.0
  - pycparser=2.19
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.3.0
  - pysocks=1.6.8
  - pytest=4.0.1
  - pytest-arraydiff=0.2
  - pytest-astropy=0.4.0
  - pytest-doctestplus=0.2.0
  - pytest-openfiles=0.3.1
  - pytest-remotedata=0.3.1
  - python=3.7.1
  - python-dateutil=2.7.5
  - pytz=2018.7
  - pyyaml=3.13
  - readline=7.0
  - requests=2.20.1
  - scipy=1.1.0
  - setuptools=40.6.2
  - six=1.11.0
  - snowballstemmer=1.2.1
  - sphinx=1.8.2
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.1.0
  - sqlite=3.25.3
  - tk=8.6.8
  - tornado=5.1.1
  - urllib3=1.23
  - werkzeug=0.14.1
  - wheel=0.32.3
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - pip:
    - asteval==0.9.13
    - astroquery==0.3.8
    - beautifulsoup4==4.6.3
    - bibtexparser==1.0.1
    - entrypoints==0.2.3
    - future==0.17.1
    - html5lib==1.0.1
    - keyring==17.0.0
    - lmfit==0.9.12
    - svo-filters==0.2.16
    - uncertainties==3.0.3
    - webencodings==0.5.1
    - git+git://github.com/lkreidberg/batman.git